[handling files]
rootdir = F:/data/1
localdir = F:/PSA BACKUP/data_1/dataframes/all_slaloms
splitdir = F:/PSA BACKUP/data_1/dataframes/splited_by_slaloms_using_detection.mat
baredir = F:/PSA BACKUP/data_1/dataframes/bare
job = split 


[EDA processing]
destinationdir = F:/data/backups/1manip/dataframes/data/eda_d2_med_mit
sampling_rate = 1000
resampling_rate = 8 
cutoff = 1 
window_size = 5 
step_size = 5
filter_order = 6

[ECG processing]
destinationdir = F:/data/backups/1manip/dataframes/data/ecg_temporal_iso
signal_type = ECG
sampling_rate = 1000
window_size =  60
anomaly_threshold = -0.07
sampleR = F:/scripts/sample_R
ecg_cols = F:/scripts/ecg_cols
rsp_cols = F:/scripts/rsp_cols


[feature extraction]
featuresdir =F:/PSA BACKUP/data_1/dataframes
# job values for dataset construction
# bare: for baseline and recuperation , split for slaloms
job = bare
# ph values
# _re_ :recuperation, _ba_: baseline arret, _bv_: baseline vehicule, _slalom_: slaloms
ph= _re_
# alpha and beta are the coefficients determining the interval of outlier detection
method = median
alpha = 1
beta = 3
# normalize_wrt values
# ba, bv
normalize_wrt = ba

[feature selection]
#path to the feature dataframe. It should be corrected and normalized
dfpath = D:/data_1/dataframes/features/slaloms_a1_n1.pkl
# number of features that we want to select (default=30)
nb_features = 30

[modeling]
# evaluation task using random quantile regressor (True or False)
evaluation = True
# train size
train_size = 0.75
# quantile level for the prediction
pqnlevel = 0.95
# threshold of score used to binarize 
thr = 2.6
# number of iterations (default=1000)
n_iterations = 15





